# Servidor
server.port=8082
spring.application.name=ms-gestion-kpi

# MongoDB Atlas — la URI completa ya incluye la base de datos
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cordillera_kpi}

# Logs
logging.level.cl.cordillera=DEBUG
